use std::fs;
use std::path::Path;
use std::time::Duration;

use crate::stack::download::resolve_source;
use crate::stack::extract::{extract_zip, find_home_with_binary};
use crate::stack::process_util::{
    check_port_before_start_with_process, find_pid_by_port, is_port_listening, kill_pid,
    run_command, run_command_in, service_status, spawn_service_in, wait_for_port,
};
use crate::stack::store::{load_store, redis_runtime_conf_path, require_install_root, save_store};
use crate::stack::types::RedisInstall;

const RUNTIME_CONF_NAME: &str = "devtools-redis.conf";

pub fn install(
    source_path: Option<&str>,
    port: u16,
    version_name: &str,
    version_id: Option<&str>,
) -> Result<RedisInstall, String> {
    let mut store = load_store();
    let install_root = require_install_root()?;
    let source = resolve_source("redis", source_path, version_id)?;
    let base = install_root.join("redis");
    fs::create_dir_all(&base).map_err(|e| e.to_string())?;

    if source.is_file() {
        extract_zip(&source, &base)?;
    }
    let scan_root = if source.is_file() { &base } else { &source };
    let home_dir = find_home_with_binary(scan_root, &["redis-server.exe"])?;

    let install = RedisInstall {
        version_label: version_name.to_string(),
        home_dir: home_dir.to_string_lossy().into_owned(),
        port,
        pid: None,
    };
    store.redis = Some(install.clone());
    save_store(&store)?;
    write_config(&install_root, &install)?;
    Ok(install)
}

pub fn write_config(install_root: &Path, install: &RedisInstall) -> Result<(), String> {
    let home = Path::new(&install.home_dir);
    let conf_path = redis_runtime_conf_path(home);
    let data_dir = install_root.join("redis").join("data");
    fs::create_dir_all(&data_dir).map_err(|e| e.to_string())?;
    let conf = format!(
        r#"# Generated by dev-tools
bind 127.0.0.1
port {port}
dir {dir}
appendonly yes
maxmemory 256mb
protected-mode yes
"#,
        port = install.port,
        dir = path_forward(&data_dir)
    );
    fs::write(&conf_path, conf).map_err(|e| e.to_string())
}

pub fn uninstall() -> Result<(), String> {
    let mut store = load_store();
    if let Some(redis) = store.redis.take() {
        let _ = stop(&redis);
    }
    save_store(&store)
}

pub fn start() -> Result<RedisInstall, String> {
    let mut store = load_store();
    let install = store.redis.as_ref().ok_or("Redis 尚未安装")?.clone();
    if let Some(running_pid) = check_port_before_start_with_process(
        install.port,
        install.pid,
        "Redis",
        Some("redis-server.exe"),
    )? {
        if let Some(ref mut r) = store.redis {
            if r.pid.is_none() {
                r.pid = Some(running_pid);
                save_store(&store)?;
            }
        }
        return Ok(install);
    }
    let root = store.install_root.as_ref().ok_or("安装目录未设置")?;
    write_config(Path::new(root), &install)?;

    let home = Path::new(&install.home_dir);
    let server = home.join("redis-server.exe");
    if !server.exists() {
        return Err(format!("未找到 redis-server.exe: {}", server.display()));
    }

    spawn_service_in(&server, Some(home), &[RUNTIME_CONF_NAME])?;

    if !wait_for_port(install.port, Duration::from_secs(8)) {
        let diag = diagnose_start_failure(&server, home);
        return Err(format!(
            "Redis 启动失败，端口 {} 未监听。\n{diag}",
            install.port
        ));
    }

    let pid = find_pid_by_port(install.port);
    if let Some(ref mut r) = store.redis {
        r.pid = pid;
        save_store(&store)?;
    }
    store.redis.clone().ok_or_else(|| "Redis 状态丢失".into())
}

pub fn stop(install: &RedisInstall) -> Result<(), String> {
    let home = Path::new(&install.home_dir);
    let cli = home.join("redis-cli.exe");
    if cli.exists() {
        let _ = run_command(
            &cli,
            &["-p", &install.port.to_string(), "shutdown"],
        );
        std::thread::sleep(std::time::Duration::from_millis(400));
    }
    if is_port_listening(install.port) {
        if let Some(pid) = install.pid.or_else(|| find_pid_by_port(install.port)) {
            kill_pid(pid)?;
        }
    }
    let mut store = load_store();
    if let Some(ref mut r) = store.redis {
        r.pid = None;
        save_store(&store)?;
    }
    Ok(())
}

pub fn stop_from_store() -> Result<RedisInstall, String> {
    let install = load_store().redis.ok_or("Redis 尚未安装")?;
    stop(&install)?;
    load_store().redis.ok_or_else(|| "Redis 状态丢失".into())
}

pub fn status(install: &RedisInstall) -> crate::stack::types::ServiceStatus {
    service_status(install.port, install.pid)
}

pub fn runtime_conf_path(install: &RedisInstall) -> std::path::PathBuf {
    redis_runtime_conf_path(Path::new(&install.home_dir))
}

fn diagnose_start_failure(server: &Path, home: &Path) -> String {
    let mut parts = vec![format!(
        "配置文件: {}",
        redis_runtime_conf_path(home).display()
    )];

    if let Ok(output) = run_command_in(server, Some(home), &["--version"]) {
        let version = String::from_utf8_lossy(&output.stdout);
        if !version.trim().is_empty() {
            parts.push(format!("版本: {}", version.trim()));
        }
    }

    // 用 --test-memory 1 会快速退出并输出配置加载错误
    if let Ok(output) = run_command_in(server, Some(home), &[RUNTIME_CONF_NAME, "--test-memory", "1"]) {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        let combined = format!("{stdout}{stderr}").trim().to_string();
        if !combined.is_empty() {
            parts.push(format!("诊断输出:\n{combined}"));
        }
    }

    parts.join("\n")
}

fn path_forward(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
