use std::path::Path;

pub fn render_my_ini(
    engine: crate::stack::types::DbEngine,
    home_dir: &Path,
    data_dir: &Path,
    logs_dir: &Path,
    port: u16,
) -> String {
    let basedir = path_for_ini(home_dir);
    let datadir = path_for_ini(data_dir);
    let log_error = path_for_ini(&logs_dir.join("error.log"));
    let engine_comment = match engine {
        crate::stack::types::DbEngine::Mysql => "MySQL",
        crate::stack::types::DbEngine::MariaDb => "MariaDB",
    };

    match engine {
        crate::stack::types::DbEngine::Mysql => format!(
            r#"# Generated by dev-tools — {engine_comment} green install
[mysqld]
basedir={basedir}
datadir={datadir}
port={port}
bind-address=127.0.0.1
log-error={log_error}
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
default_authentication_plugin=mysql_native_password
explicit_defaults_for_timestamp=1
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
max_connections=200

[client]
host=127.0.0.1
port={port}
default-character-set=utf8mb4

[mysql]
host=127.0.0.1
port={port}
default-character-set=utf8mb4
"#
        ),
        crate::stack::types::DbEngine::MariaDb => format!(
            r#"# Generated by dev-tools — {engine_comment} green install
[mysqld]
basedir={basedir}
datadir={datadir}
port={port}
bind-address=127.0.0.1
log-error={log_error}
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
max_connections=200

[client]
host=127.0.0.1
port={port}
default-character-set=utf8mb4

[mysql]
host=127.0.0.1
port={port}
default-character-set=utf8mb4
"#
        ),
    }
}

pub fn write_config(install_root: &Path, install: &crate::stack::types::MysqlInstall) -> Result<(), String> {
    use std::fs;
    use crate::stack::store::mysql_paths;

    let (my_ini_path, data_dir, logs_dir) = mysql_paths(install_root, install.engine);
    fs::create_dir_all(&logs_dir).map_err(|e| e.to_string())?;
    let home = Path::new(&install.home_dir);
    let my_ini = render_my_ini(install.engine, home, &data_dir, &logs_dir, install.port);
    fs::write(&my_ini_path, my_ini).map_err(|e| e.to_string())
}

fn path_for_ini(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ini_uses_forward_slashes() {
        let ini = render_my_ini(
            crate::stack::types::DbEngine::Mysql,
            Path::new(r"D:\dev-env\mysql\mysql-8.4.0-winx64"),
            Path::new(r"D:\dev-env\mysql\data"),
            Path::new(r"D:\dev-env\mysql\logs"),
            3307,
        );
        assert!(ini.contains("basedir=D:/dev-env/mysql/mysql-8.4.0-winx64"));
        assert!(ini.contains("port=3307"));
    }

    #[test]
    fn mariadb_ini_skips_mysql_only_options() {
        let ini = render_my_ini(
            crate::stack::types::DbEngine::MariaDb,
            Path::new(r"D:\dev-env\mysql\mariadb-11.4.2-winx64"),
            Path::new(r"D:\dev-env\mysql\data-mariadb"),
            Path::new(r"D:\dev-env\mysql\logs"),
            3307,
        );
        assert!(!ini.contains("default_authentication_plugin"));
    }
}
