name: Sync to Gitee

on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitee
        uses: wearerequired/git-mirror-action@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
        with:
          source-repo: git@github.com:caojiabin2012/tool-kit.git
          destination-repo: git@gitee.com:caojiabin/tool-kit.git
